### ISSUE TITLE
require: cannot load such file -- diakonos

### ISSUE THREAD

**Issue by ulysses4ever** [Pistos/diakonos#82]
I installed latest version from tarball. The install script seemed to finish happily. Trying to run gives this:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- diakonos (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ulysses/bin/diakonos:3:in `<main>'
```

**Comment by Pistos** [comment]
Could you provide the contents of `/home/ulysses/bin/diakonos`?  Are you using RVM?  rbenv?

**Comment by Pistos** [comment]
And could you paste the output of the installation script with a `-v` option on it (verbose) and `-p` (pretend)?

**Comment by ulysses4ever** [comment]
> Could you provide the contents of /home/ulysses/bin/diakonos?
```
$ cat /home/ulysses/bin/diakonos 
#!/usr/bin/ruby2.3

require 'diakonos'

$diakonos = Diakonos::Diakonos.new( ARGV )
$diakonos.start
```
> Are you using RVM? rbenv?

I know nothing about `ruby`. How do I find out?

> And could you paste the output of the installation script with a -v option on it (verbose) 

See here (quite a bit): https://pastebin.com/mNz8spEU

> and -p (pretend)?
```
$ ruby install.rb -p --dest-dir /home/ulysses/diakonos 
(Dry run only; not actually writing any files or directories)


Diakonos 0.9.4 (October 26, 2014) installed.

If Diakonos has been installed with a Linux distro's package manager,
uninstall using that package manager.
If Diakonos has been installed independently of a package manager,
uninstall by running:

  diakonos --uninstall

Thank you for installing Diakonos.  Have a stupendous day!  :)
```

**Comment by Pistos** [comment]
Version 0.9.4 is very old.  Try to get 0.9.6, or, if you can manage it, get the very latest code from the git repository.

If you don't know if you are using RVM or rbenv, then you're not using either one, most likely.  :)

Don't use `--dest-dir`, that flag is for Linux distro package managers.  What you probably meant to use is `--prefix`.  But you should `rm -rf /home/ulysses/diakonos` first, to clean out any existing installation.

What Linux distro are you using?

**Comment by ulysses4ever** [comment]
I redo installation for 0.9.6: it gives me the just same result. Maybe I should use some ruby env variables to point it to `diakonos` installation? Given that `diakonos` installed inside home directory. 

OS: Debian 4.9.2-2.

**Comment by Pistos** [comment]
I think Debian dropped their Diakonos package, even though Ubuntu might still have one.  Because of this, why don't you try using RVM first to get Ruby (version 2.4.x), and then, once you have selected a particular Ruby version with RVM, the Diakonos installation should go much more smoothly.

RVM installation instructions are here: https://rvm.io/rvm/install

**Comment by ulysses4ever** [comment]
I (seemed to) install `rvm`. What should I do next? [GitHub README](https://github.com/Pistos/diakonos) says: "After installing Diakonos under RVM..." but it does not say how to actually install Diakonos under RVM.

**Comment by Pistos** [comment]
Try these steps:

```
% rvm install 2.4.1
% rvm use 2.4.1
% gem install curses
% mkdir -p ~/etc
% cd path/to/diakonos-checkout
% ruby install.rb --conf-dir ~/etc
```

After that, you *may* need to adjust your `PATH` to get it to run from anywhere, but I can help you with that after.

**Comment by ulysses4ever** [comment]
Seems that `rvm` calls (during `install` stap) `apt-get` which requires `sudo` and I don't have root privileges on the machine.

**Comment by Pistos** [comment]
`rvm` does not require root.  Do this first, then try again:

```
% rvm autolibs read-only
```

If you are familiar with IRC, you can come to irc.freenode.net #mathetes and I can help you a little more quickly.

**Comment by ulysses4ever** [comment]
Sorry, I'm not familiar with IRC and it is easier for me to talk in comment-mode rather than instantly.

`rvm autolibs read-only` helped -- thanks! Every command you wrote worked well. But the run of `diakonos` still dies with the same message. Note that I used `ruby install.rb --conf-dir ~/etc --prefix ~/diakonos` for installation. You can see that `ruby` 2.4 is indeed used (it was installed via `rvm`).

```
~/diakonos$ ./bin/diakonos 
/home/ulysses/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- diakonos (LoadError)
	from /home/ulysses/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bin/diakonos:3:in `<main>'
```

**Comment by Pistos** [comment]
Don't use `./bin/diakonos`, that means something else.  Just 

```
% cd ~
% diakonos anyfile.txt
```

The directory you are in should not matter, the `diakonos` executable is supposed to be globally available as long as you have switched to Ruby 2.4.1 with RVM.

**Comment by ulysses4ever** [comment]
I can't install it without `--prefix` (*Permission denied*). If I use prefix, than for your last suggestion I get *diakonos: command not found*.

**Comment by Pistos** [comment]
Can you see if you can find the installed executable within RVM's subtree?  Try this: `ls ~/.rvm/rubies/*/bin/diakonos`  And then switch to the matching RVM ruby version, then execute the full path of whatever is listed.  For example, on my machine, it might be: `rvm use 2.4.0; /home/pistos/.rvm/rubies/ruby-2.4.0/bin/diakonos`

I apologize that you're having this much trouble, but I appreciate you sticking around to find a resolution!

**Comment by Pistos** [comment]
How are things going with this, @ulysses4ever ?

**Comment by ulysses4ever** [comment]
I'm very sorry, I'm at the high pressure of a deadline last week. I hope I'll be able to come back to this thing later this week.

**Comment by Pistos** [comment]
No problem, I was just curious.  Of course your normal responsibilities and obligations take precedence.  :)

**Comment by dmitriyK1** [comment]
I have the same issue while trying to run it

**Comment by Pistos** [comment]
@dmitriyK1 Please provide some details about your environment, and what you have tried.

**Comment by Pistos** [comment]
Closing due to inactivity.
